#include QMK_KEYBOARD_H

enum layers {
    _L0 = 0,
    _L1,
    _L2,
    _L3,
    _L4,
    _L5,
    _L6,
    _L7,
    _L8,
    _L9
};

#define FN_ZERO LT(_L9, KC_KP_0)

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

    [_L0] = LAYOUT(KC_KP_7, KC_KP_8, KC_KP_9, KC_KP_4, KC_KP_5, KC_KP_6, KC_KP_1, KC_KP_2, KC_KP_3, FN_ZERO),
    [_L1] = LAYOUT(KC_MUTE, KC_VOLU, KC_VOLD, KC_MSTP, KC_UP,   KC_MPLY, KC_LEFT, KC_DOWN, KC_RGHT, KC_TRNS),
    [_L2] = LAYOUT(KC_PPLS, KC_PMNS, KC_PAST, KC_PSLS, KC_PERC, KC_COMM, KC_PDOT, KC_EQL,  KC_PENT, MO(_L9)),
    [_L3] = LAYOUT(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
    [_L4] = LAYOUT(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
    [_L5] = LAYOUT(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
    [_L6] = LAYOUT(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
    [_L7] = LAYOUT(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
    [_L8] = LAYOUT(KC_TRNS, KC_TRNS, RESET, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
    [_L9] = LAYOUT(DF(_L6), DF(_L7), DF(_L8), DF(_L3), DF(_L4), DF(_L5), DF(_L0), DF(_L1), DF(_L2), KC_TRNS)

};
